package snill.client.api.storages.implement.helpertstorages.enumvar;

import com.jcraft.jorbis.Block;
import snill.client.client.modules.impl.combat.*;
import snill.client.client.modules.impl.misc.*;
import snill.client.client.modules.impl.movement.*;
import snill.client.client.modules.impl.player.*;

import snill.client.client.modules.impl.render.*;
public interface ModuleRewords {
    AirStuck airStuck = AirStuck.INSTANCE;
    Arrows arrows = Arrows.INSTANCE;
    Aura aura = Aura.INSTANCE;
    AntiBot antibot = AntiBot.INSTANCE;
    AutoAccept autoAccept = AutoAccept.INSTANCE;
    AhHelper ahHelper = AhHelper.INSTANCE;
    SearchHelper searchHelper = SearchHelper.INSTANCE;
    LeaveTracker leavetracker = LeaveTracker.INSTANCE;
    AutoDuel autoDuel = AutoDuel.INSTANCE;
    AutoLeave autoLeave = AutoLeave.INSTANCE;
    AutoExplosion autoExplosion = AutoExplosion.INSTANCE;
    NameProtect nameProtect = NameProtect.INSTANCE;
    Chams chams = Chams.INSTANCE;
    ClientSounds clientSounds = ClientSounds.INSTANCE;
    AutoTool autoTool = AutoTool.INSTANCE;
    AutoTotem autoTotem = AutoTotem.INSTANCE;
    BlockOverlay blockOverlay = BlockOverlay.INSTANCE;
    ClickPearl clickPearl = ClickPearl.INSTANCE;
    Cosmetics cosmetics = Cosmetics.INSTANCE;
    Cubes cubes = Cubes.INSTANCE;
    AutoRakushka test = AutoRakushka.INSTANCE;
    KillEffect killEffect = KillEffect.INSTANCE;
    BlockESP blockesp = BlockESP.INSTANCE;
    ElytraBoost elytraBoost = ElytraBoost.INSTANCE;
    ElytraMotion elytraMotion = ElytraMotion.INSTANCE;
    ElytraSwap elytraSwap = ElytraSwap.INSTANCE;
    ElytraTarget elytraTarget = ElytraTarget.INSTANCE;
    EntityESP entityESP = EntityESP.INSTANCE;
    FreeCam freeCam = FreeCam.INSTANCE;
    FullBright fullBright = FullBright.INSTANCE;
    GrimGlide grimGlide = GrimGlide.INSTANCE;
    HitBubbles hitBubbles = HitBubbles.INSTANCE;
    Particles particles = Particles.INSTANCE;
    DashTrails dashTrails = DashTrails.INSTANCE;
    Interface interfaceModule = Interface.INSTANCE;
    ItemReplacer itemReplacer = ItemReplacer.INSTANCE;
    InterpolateF5 interpolateF5 = InterpolateF5.INSTANCE;
    InventoryWalk inventoryWalk = InventoryWalk.INSTANCE;
    ItemScroller itemScroller = ItemScroller.INSTANCE;
    ItemRelease itemRelease = ItemRelease.INSTANCE;
    JumpCircle jumpCircle = JumpCircle.INSTANCE;
    NoJumpDelay noJumpDelay = NoJumpDelay.INSTANCE;
    NoPush noPush = NoPush.INSTANCE;
    NoControllerWeb noControllerWeb = NoControllerWeb.INSTANCE;
    NoWeb noWeb = NoWeb.INSTANCE;
    PacketCriticals packetCriticals = PacketCriticals.INSTANCE;
    Pets pets = Pets.INSTANCE;
    Projectile projectile = Projectile.INSTANCE;
    FireworkESP fireworkESP = FireworkESP.INSTANCE;
    FastExp fastExp = FastExp.INSTANCE;
    Removals removals = Removals.INSTANCE;
    SeeInvisibles seeInvisibles = SeeInvisibles.INSTANCE;
    ShaderEsp shaderEsp = ShaderEsp.INSTANCE;
    ShaderHands shaderHands = ShaderHands.INSTANCE;
    ShulkerPreview shulkerPreview = ShulkerPreview.INSTANCE;
    Sonar sonar = Sonar.INSTANCE;
    SmoothSwapping smoothSwapping = SmoothSwapping.INSTANCE;
    Speed speed = Speed.INSTANCE;
    Sprint sprint = Sprint.INSTANCE;
    SwingAnimations swingAnimations = SwingAnimations.INSTANCE;
    TargetESP targetESP = TargetESP.INSTANCE;
    HitEffect hitEffect = HitEffect.INSTANCE;
    TotemAngel totemAngel = TotemAngel.INSTANCE;
    TotemEffect totemEffect = TotemEffect.INSTANCE;
    ViewModel viewModel = ViewModel.INSTANCE;
    WorldTweaks worldTweaks = WorldTweaks.INSTANCE;
    AutoSwap autoSwap = AutoSwap.INSTANCE;
    AimBot aimBot = AimBot.INSTANCE;
    ScoreboardHP scoreboardHP = ScoreboardHP.INSTANCE;
    PotionTracker potionTracker = PotionTracker.INSTANCE;
    AntiThorns antithorns = AntiThorns.INSTANCE;
    ServerHelper serverHelper = ServerHelper.INSTANCE;
    LootTracker lootTracker = LootTracker.INSTANCE;
    HitMarker hitMarker = HitMarker.INSTANCE;
    Trails trails = Trails.INSTANCE;
    Tracers tracers = Tracers.INSTANCE;
    Trajectories trajectories = Trajectories.INSTANCE;
    Velocity velocity = Velocity.INSTANCE;
    NoSlow noSlow = NoSlow.INSTANCE;
    TargetStrafe targetStrafe = TargetStrafe.INSTANCE;
    MaceHelper maceHelper = MaceHelper.INSTANCE;
    AutoBuff autoBuff = AutoBuff.INSTANCE;
    AutoEat autoEat = AutoEat.INSTANCE;
    ChestStealer chestStealer = ChestStealer.INSTANCE;
    AnchorAura anchorAura = AnchorAura.INSTANCE;
    AutoWeb autoWeb = AutoWeb.INSTANCE;
    AutoArmor autoArmor = AutoArmor.INSTANCE;
    FastBreak fastBreak = FastBreak.INSTANCE;
    Browser browser = Browser.INSTANCE;
    HitSounds hitSounds = HitSounds.INSTANCE;
    CustomCrosshair customCrosshair = CustomCrosshair.INSTANCE;
    AspectRatio aspectRatio = AspectRatio.INSTANCE;
}
